Repository KDRUCSProjects/online-pharma-2023111, pull requests merged in 2023-08, with the labels that each got.

#152 pagination
  src/services/api/admin.py
  src/services/api/views/data/ad.py
  src/services/api/views/data/pagination.py
  src/services/api/views/data/topSelling.py
  src/services/frontend/src/components/Ad/AdList.js
  src/services/frontend/src/components/Ad/ad detail/AdDetail.js
  src/services/frontend/src/components/Api/Api.js
  src/services/frontend/src/components/Featured Products/FeaturedProducts.js
  src/services/frontend/src/components/admin/components/order/OrderList.js
  src/services/frontend/src/components/admin/components/order/PrescriptionList.js
  src/services/frontend/src/components/admin/components/report/OrderReport.js
  src/services/frontend/src/components/category/MobileCategory.js
  src/services/frontend/src/components/footer/Footer.js
  src/services/frontend/src/components/layout/MobileSidebar.js
  src/services/frontend/src/components/layout/SideBarDrawer.js
  src/services/frontend/src/components/router/RouteList.js
  src/services/frontend/src/components/top selling item/TopSellingItem.js
Labels: High

#156 layout-searchbar.
  src/services/frontend/src/components/footer/Footer.js
  src/services/frontend/src/components/layout/SearchBar.js
Labels: bug

#155 bill created.
  src/services/frontend/src/components/admin/components/bill/Bill.js
  src/services/frontend/src/components/admin/components/order/OrderList.js
Labels: enhancement

#160 fixed user profile
  src/services/frontend/src/components/order/OrderCart.js
  src/services/frontend/src/components/user/Profile.js
Labels: bug

#157 fixed order-list
  src/services/frontend/src/components/order/OrderCart.js
Labels: bug

#161 warning
  src/services/frontend/src/components/category/Category.js
  src/services/frontend/src/components/footer/Footer.js
  src/services/frontend/src/components/layout/Home.js
  src/services/frontend/src/components/slider/Slider.js
Labels: bug

#162 fixed adlist page.
  src/services/frontend/src/components/Ad/AdList.js
  src/services/frontend/src/components/Ad/ad detail/AdDetail.js
  src/services/frontend/src/components/layout/Home.js
Labels: bug

#163 featured-product
  src/services/frontend/src/components/Ad/AdCard.js
  src/services/frontend/src/components/Featured Products/FeaturedProducts.js
  src/services/frontend/src/components/top selling item/TopSellingItem.js
Labels: bug

#166 Cancel Order
  src/services/account/serializers.py
  src/services/frontend/src/components/Api/Api.js
  src/services/frontend/src/components/layout/BottomNavigate.js
  src/services/frontend/src/components/layout/SearchBar.js
  src/services/frontend/src/components/order/OrderCart.js
Labels: enhancement

#165 prescription-detail
  src/services/frontend/src/components/admin/components/order/PrescriptionDetails.js
  src/services/frontend/src/components/admin/components/order/PrescriptionList.js
  src/services/frontend/src/components/order/Prescription.js
  src/services/frontend/src/components/router/RouteList.js
  src/services/frontend/static/images/prescription/2023/08/15/06823.webp
  src/services/frontend/static/images/prescription/2023/08/15/06823_9d0UJZ8.webp
  src/services/frontend/static/images/prescription/2023/08/15/10228.webp
  src/services/frontend/static/images/prescription/2023/08/15/1_UKFoUhUA6otCuRp2lWS6UQ.png
  src/services/frontend/static/images/prescription/2023/08/15/1_UKFoUhUA6otCuRp2lWS6UQ_oif3kqX.png
Labels: enhancement

#167 localization.
  src/services/frontend/src/components/Featured Products/FeaturedProducts.js
  src/services/frontend/src/components/category/Category.js
  src/services/frontend/src/components/feedback/ComplaintForm.js
  src/services/frontend/src/components/feedback/FeedBack.js
  src/services/frontend/src/components/feedback/FeedbackForm.js
  src/services/frontend/src/components/footer/Footer.js
  src/services/frontend/src/components/layout/NavBar.js
  src/services/frontend/src/components/layout/SearchBar.js
  src/services/frontend/src/components/location/Location.js
  src/services/frontend/src/components/top selling item/TopSellingItem.js
  src/services/frontend/src/components/user/ChangePassword.js
  src/services/frontend/src/components/user/Login.js
  src/services/frontend/src/components/user/Registration.js
  src/services/frontend/src/locale/Dari/Home.js
  src/services/frontend/src/locale/Dari/Location.js
  src/services/frontend/src/locale/Dari/Login.js
  src/services/frontend/src/locale/Dari/UserRegister.js
  src/services/frontend/src/locale/English/Home.js
  src/services/frontend/src/locale/English/Location.js
  src/services/frontend/src/locale/English/Login.js
  src/services/frontend/src/locale/English/UserRegister.js
  src/services/frontend/src/locale/Pashto/Home.js
  src/services/frontend/src/locale/Pashto/Login.js
  src/services/frontend/src/locale/Pashto/UserRegister.js
Labels: enhancement

#168 Ording
  src/services/api/models/data/ad.py
  src/services/api/views/data/order.py
  src/services/api/views/data/prescription.py
  src/services/frontend/src/components/admin/components/bill/Bill.js
  src/services/frontend/src/components/admin/components/order/OrderList.js
  src/services/frontend/static/images/prescription/2023/08/16/Screenshot_from_2023-08-16_05-36-24.png
Labels: enhancement
