Repository KDRUCSProjects/online-pharma-2023111, pull requests merged in 2023-07, with the labels that each got.

#120 Feedback endPoint
  src/services/frontend/src/components/feedback/ComplaintForm.js
  src/services/frontend/src/components/feedback/FeedbackForm.js
  src/services/frontend/src/components/order/Prescription.js
  src/services/frontend/static/images/prescription/2023/07/21/03904-1.webp
  src/services/frontend/static/images/prescription/2023/07/21/03904-1_c2OJa7R.webp
  src/services/frontend/static/images/prescription/2023/07/21/13621.webp
  src/services/frontend/static/images/prescription/2023/07/21/17569.webp
Labels: enhancement

#118 menu bar.
  src/services/frontend/src/components/App.js
  src/services/frontend/src/components/contact us/Contact.js
  src/services/frontend/src/components/layout/MenuBar.js
  src/services/frontend/src/components/layout/NavBar.js
  src/services/frontend/src/components/layout/SearchBar.js
  src/services/frontend/src/components/mobil address/MobileAddress.js
  src/services/frontend/src/components/mobileviewaddres/MobileAddres.js
Labels: enhancement, High

#122 bottom navigation created.
  src/services/frontend/src/components/App.js
  src/services/frontend/src/components/admin/components/category/MobileCategory.js
  src/services/frontend/src/components/layout/BottomNavigate.js
  src/services/frontend/src/components/user/Profile.js
  src/services/frontend/src/index.js
Labels: enhancement, High

#123 Route Fix
  src/services/api/migrations/0003_prescription_status.py
  src/services/frontend/src/components/Ad/ad detail/AdDetail.js
  src/services/frontend/src/components/Ad/ad detail/DescriptionDetail.js
  src/services/frontend/src/components/Ad/ad detail/UsedForDetail.js
  src/services/frontend/src/components/Ad/ad detail/WorkDetail.js
  src/services/frontend/src/components/App.js
  src/services/frontend/src/components/admin/components/order/PrescriptionList.js
  src/services/frontend/src/components/layout/SearchBar.js
  src/services/frontend/src/components/router/RouteList.js
  src/services/frontend/src/index.js
Labels: invalid

#127 location_endpoint
  src/services/api/serializers/data/prescription.py
  src/services/frontend/src/components/App.js
  src/services/frontend/src/components/admin/components/order/PrescriptionList.js
  src/services/frontend/src/components/layout/SearchBar.js
  src/services/frontend/src/components/location/Location.js
  src/services/frontend/src/components/location/MobileAddress.js
  src/services/frontend/src/components/order/Prescription.js
  src/services/frontend/src/components/services/LocalStorageService.js
Labels: enhancement, High

#128 login & register.
  src/services/account/serializers.py
  src/services/frontend/src/components/App.js
  src/services/frontend/src/components/category/MobileCategory.js
  src/services/frontend/src/components/layout/MenuBar.js
  src/services/frontend/src/components/router/RouteList.js
  src/services/frontend/src/components/user/Login.js
  src/services/frontend/src/components/user/Profile.js
  src/services/frontend/src/components/user/Registration.js
Labels: bug

#130 forgot password fixed
  src/services/frontend/src/components/layout/NavBar.js
  src/services/frontend/src/components/location/Location.js
  src/services/frontend/src/components/router/RouteList.js
  src/services/frontend/src/components/user/ChangePassword.js
  src/services/frontend/src/components/user/Login.js
  src/services/frontend/src/components/user/Registration.js
  src/services/frontend/src/components/user/ResetPassword.js
  src/services/frontend/src/components/user/SendPasswordResetEmail.js
Labels: bug

#131 loading action.
  src/services/frontend/src/components/user/ChangePassword.js
  src/services/frontend/src/components/user/Registration.js
  src/services/frontend/src/components/user/ResetPassword.js
  src/services/frontend/src/components/user/SendPasswordResetEmail.js
Labels: bug

#132 Validate Login Form
  src/services/frontend/package.json
  src/services/frontend/src/components/Ad/AdList.js
  src/services/frontend/src/components/Ad/ad detail/AdDetail.js
  src/services/frontend/src/components/Validators/Validators.js
  src/services/frontend/src/components/user/Login.js
Labels: enhancement, High

#91 order list page
  src/services/frontend/src/components/footer/Footer.js
  src/services/frontend/src/components/order/AllOrder.js
  src/services/frontend/src/components/order/CancelledOrder.js
  src/services/frontend/src/components/order/CompleteOrder.js
  src/services/frontend/src/components/order/OrderLists.js
  src/services/frontend/src/components/order/PendingOrder.js
  src/services/frontend/src/components/router/RouteList.js
  src/services/frontend/src/components/user/Profile.js
Labels: enhancement

#134 Cart Shopping Data
  src/services/frontend/src/components/Ad/ad detail/AdDetail.js
  src/services/frontend/src/components/features/cart context/CartReducer.js
  src/services/frontend/src/components/features/cart context/cart_context.js
  src/services/frontend/src/components/layout/SearchBar.js
  src/services/frontend/src/components/order/add to cart/CartItem.js
  src/services/frontend/src/components/order/add to cart/ShoppingCart.js
  src/services/frontend/src/components/router/RouteList.js
  src/services/frontend/src/index.js
Labels: enhancement, High

#141 [orders history]: showing order of logged user in user profile
  src/services/frontend/src/components/Ad/ad detail/AdDetail.js
  src/services/frontend/src/components/Ad/ad detail/Generic.js
  src/services/frontend/src/components/features/cart context/CartReducer.js
  src/services/frontend/src/components/features/cart context/cart_context.js
  src/services/frontend/src/components/order/AllOrder.js
  src/services/frontend/src/components/order/CancelledOrder.js
  src/services/frontend/src/components/order/CompleteOrder.js
  src/services/frontend/src/components/order/OrderCart.js
  src/services/frontend/src/components/order/OrderLists.js
  src/services/frontend/src/components/order/PendingOrder.js
  src/services/frontend/src/components/top selling item/TopSellingItem.js
  src/services/frontend/src/components/user/Profile.js
Labels: enhancement, High

#144 footer-fonts
  src/services/frontend/src/components/footer/Footer.js
Labels: bug

#143 shopping-carts
  src/services/frontend/src/components/order/add to cart/CartItem.js
  src/services/frontend/src/components/user/Login.js
Labels: bug

#142 fixed adcart
  src/services/frontend/src/components/Ad/AdCard.js
  src/services/frontend/static/images/drugs/drug/2023/07/26/03873.webp
  src/services/frontend/static/images/drugs/drug/2023/07/26/03873_N5fAL8f.webp
  src/services/frontend/static/images/drugs/drug/2023/07/26/06823.webp
  src/services/frontend/static/images/drugs/drug/2023/07/26/06823_fqjaAeP.webp
  src/services/frontend/static/images/drugs/drug/2023/07/26/10228.webp
  src/services/frontend/static/images/drugs/drug/2023/07/26/11468.webp
  src/services/frontend/static/images/drugs/drug/2023/07/26/11468_GM72WL5.webp
  src/services/frontend/static/images/drugs/drug/2023/07/26/1_1Wqnq0Q.webp
  src/services/frontend/static/images/drugs/drug/2023/07/26/1_1_O1UUWdk.webp
Labels: bug

#148 search-point
  src/services/api/views/data/ad.py
  src/services/frontend/src/components/Ad/AdCard.js
  src/services/frontend/src/components/Ad/AdList.js
  src/services/frontend/src/components/Ad/ad detail/AdDetail.js
  src/services/frontend/src/components/features/cart context/CartReducer.js
  src/services/frontend/src/components/layout/Home.js
  src/services/frontend/src/components/location/Location.js
  src/services/frontend/src/components/order/add to cart/ShoppingCart.js
  src/services/frontend/src/components/router/RouteList.js
Labels: bug

#150 Logo of website
  src/services/frontend/src/components/footer/Footer.js
  src/services/frontend/src/components/layout/NavBar.js
  src/services/frontend/src/components/slider/Images.js
  src/services/frontend/static/images/drugs/drug/2023/07/28/12525.webp
  src/services/frontend/static/images/logo/footer.png
  src/services/frontend/static/images/logo/header.png
  src/services/frontend/static/images/logo/icon.avif
  src/services/frontend/static/images/prescription/2023/07/28/25507.webp
  src/services/frontend/static/images/slider/slide5.png
  src/services/frontend/templates/frontend/index.html
Labels: High

#151 fix cart item
  src/services/frontend/src/components/order/add to cart/CartItem.js
  src/services/frontend/src/components/order/add to cart/ShoppingCart.js
Labels: invalid
